spring:
  application:
    name: config-server
  profiles:
    active:
      - native
#      - git
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/egorbekhterev/shoponline-config
        native:
          search-+locations: classpath:/config

server:
  port: 8071

#encrypt:
#  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo


#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"